IS7/Models/WorkHistory.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHistory
    {
        public string MNumber { get; set; }
        public string CompanyName { get; set; }
        public string TitleName { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> FTE { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Title Title { get; set; }
        public virtual User User { get; set; }
    }
}

IS7/Controllers/WorkHistoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IS7.Models;

namespace IS7.Controllers
{

    public class WorkHistoriesController : Controller
    {
        private IS7_DBEntities db = new IS7_DBEntities();

        // GET: WorkHistories
        public ActionResult Index(string searchBy, string search)
        { if (searchBy == "CompanyName")
            {
                return View(db.WorkHistories.Where(x => x.CompanyName.StartsWith(search) || search == null).ToList());
            }        
            else 
            { 
             return View(db.WorkHistories.Where(x => x.TitleName.StartsWith(search) || search == null).ToList());
            }
        }

        //{
        //    var workHistories = db.WorkHistories.Include(w => w.Company).Include(w => w.Title).Include(w => w.User);
        //    return View(await workHistories.ToListAsync());
        //}

        // GET: WorkHistories/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkHistory workHistory = await db.WorkHistories.FindAsync(id);
            if (workHistory == null)
            {
                return HttpNotFound();
            }
            return View(workHistory);
        }

        // GET: WorkHistories/Create
        public ActionResult Create()
        {
            ViewBag.CompanyName = new SelectList(db.Companies, "CompanyName", "CompanyName");
            ViewBag.TitleName = new SelectList(db.Titles, "TitleName", "TitleName");
            ViewBag.MNumber = new SelectList(db.Users, "MNumber", "LastName");
            return View();
        }

        // POST: WorkHistories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "MNumber,CompanyName,TitleName,StartDate,EndDate,FTE")] WorkHistory workHistory)
        {
            if (ModelState.IsValid)
            {
                db.WorkHistories.Add(workHistory);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CompanyName = new SelectList(db.Companies, "CompanyName", "CompanyName", workHistory.CompanyName);
            ViewBag.TitleName = new SelectList(db.Titles, "TitleName", "TitleName", workHistory.TitleName);
            ViewBag.MNumber = new SelectList(db.Users, "MNumber", "LastName", workHistory.MNumber);
            return View(workHistory);
        }

        // GET: WorkHistories/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkHistory workHistory = await db.WorkHistories.FindAsync(id);
            if (workHistory == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyName = new SelectList(db.Companies, "CompanyName", "CompanyName", workHistory.CompanyName);
            ViewBag.TitleName = new SelectList(db.Titles, "TitleName", "TitleName", workHistory.TitleName);
            ViewBag.MNumber = new SelectList(db.Users, "MNumber", "LastName", workHistory.MNumber);
            return View(workHistory);
        }

        // POST: WorkHistories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "MNumber,CompanyName,TitleName,StartDate,EndDate,FTE")] WorkHistory workHistory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(workHistory).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CompanyName = new SelectList(db.Companies, "CompanyName", "CompanyName", workHistory.CompanyName);
            ViewBag.TitleName = new SelectList(db.Titles, "TitleName", "TitleName", workHistory.TitleName);
            ViewBag.MNumber = new SelectList(db.Users, "MNumber", "LastName", workHistory.MNumber);
            return View(workHistory);
        }

        // GET: WorkHistories/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkHistory workHistory = await db.WorkHistories.FindAsync(id);
            if (workHistory == null)
            {
                return HttpNotFound();
            }
            return View(workHistory);
        }

        // POST: WorkHistories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            WorkHistory workHistory = await db.WorkHistories.FindAsync(id);
            db.WorkHistories.Remove(workHistory);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IS7/Views/WorkHistories/Create.cshtml
@model IS7.Models.WorkHistory

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WorkHistory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MNumber, "Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MNumber", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, "CompanyName", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanyName", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TitleName, "TitleName", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TitleName", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TitleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FTE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FTE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FTE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IS7/Views/WorkHistories/Delete.cshtml
@model IS7.Models.WorkHistory

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WorkHistory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FTE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FTE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title.TitleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title.TitleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.LastName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IS7/Views/WorkHistories/Details.cshtml
@model IS7.Models.WorkHistory

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>WorkHistory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FTE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FTE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title.TitleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title.TitleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.LastName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IS7/Views/WorkHistories/Edit.cshtml
@model IS7.Models.WorkHistory

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WorkHistory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MNumber)

        @Html.HiddenFor(model => model.CompanyName)

        @Html.HiddenFor(model => model.TitleName)

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FTE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FTE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FTE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IS7/Views/WorkHistories/Index.cshtml
@model IEnumerable<IS7.Models.WorkHistory>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<p>
    @using (Html.BeginForm("Index", "WorkHistories", FormMethod.Get))
    { 
    <b>Search By:</b> 
    @Html.RadioButton("searchBy", "CompanyName", true) <text>CompanyName</text>
    @Html.RadioButton("searchBy", "TitleName") <text>TitleName</text>
    <br/>
    @Html.TextBox("search")<input type="submit" value="Search"/>
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.User.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.MNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Company.CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title.TitleName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FTE)
        </th>
        <th>Action</th>
    </tr>
@if (Model.Count() == 0)
{
    <tr>
        <td colspan="8">No rows match search criteria</td>
    </tr>
}
else 
{ 
foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.User.LastName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.User.MNumber)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Company.CompanyName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Title.TitleName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.StartDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.EndDate)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FTE)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
    </td>
</tr>
}
}
</table>