IS7/Controllers/InterviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IS7.Models;

namespace IS7.Controllers
{
    public class InterviewsController : Controller
    {
        private IS7_DBEntities db = new IS7_DBEntities();
        public ActionResult Index(string searchBy, string search)
        {
            if (searchBy == "InterviewCompany")
            {
                return View(db.Interviews.Where(x => x.InterviewCompany.StartsWith(search) || search == null).ToList());
            }
            else
            {
                return View(db.Interviews.Where(x => x.MNumber.EndsWith(search) || search == null).ToList());
            }
        }
        // GET: Interviews
        //public async Task<ActionResult> Index()
        //{
        //    var interviews = db.Interviews.Include(i => i.User);
        //    return View(await interviews.ToListAsync());
        //}

        // GET: Interviews/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interview interview = await db.Interviews.FindAsync(id);
            if (interview == null)
            {
                return HttpNotFound();
            }
            return View(interview);
        }

        // GET: Interviews/Create
        public ActionResult Create()
        {
            ViewBag.MNumber = new SelectList(db.Users, "MNumber", "LastName");
            return View();
        }

        // POST: Interviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "MNumber,InterviewCompany,InterviewDate,Offer")] Interview interview)
        {
            if (ModelState.IsValid)
            {
                db.Interviews.Add(interview);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.MNumber = new SelectList(db.Users, "MNumber", "LastName", interview.MNumber);
            return View(interview);
        }

        // GET: Interviews/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interview interview = await db.Interviews.FindAsync(id);
            if (interview == null)
            {
                return HttpNotFound();
            }
            ViewBag.MNumber = new SelectList(db.Users, "MNumber", "LastName", interview.MNumber);
            return View(interview);
        }

        // POST: Interviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "MNumber,InterviewCompany,InterviewDate,Offer")] Interview interview)
        {
            if (ModelState.IsValid)
            {
                db.Entry(interview).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.MNumber = new SelectList(db.Users, "MNumber", "LastName", interview.MNumber);
            return View(interview);
        }

        // GET: Interviews/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interview interview = await db.Interviews.FindAsync(id);
            if (interview == null)
            {
                return HttpNotFound();
            }
            return View(interview);
        }

        // POST: Interviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            Interview interview = await db.Interviews.FindAsync(id);
            db.Interviews.Remove(interview);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IS7/Views/Interviews/Create.cshtml
@model IS7.Models.Interview

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Interview</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MNumber, "Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MNumber", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InterviewCompany, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InterviewCompany, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InterviewCompany, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InterviewDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InterviewDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InterviewDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Offer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Offer)
                    @Html.ValidationMessageFor(model => model.Offer, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IS7/Views/Interviews/Delete.cshtml
@model IS7.Models.Interview

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Interview</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.InterviewDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InterviewDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Offer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Offer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.LastName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IS7/Views/Interviews/Details.cshtml
@model IS7.Models.Interview

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Interview</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.InterviewDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InterviewDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Offer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Offer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.LastName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IS7/Views/Interviews/Edit.cshtml
@model IS7.Models.Interview

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Interview</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MNumber)

        @Html.HiddenFor(model => model.InterviewCompany)

        <div class="form-group">
            @Html.LabelFor(model => model.InterviewDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InterviewDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InterviewDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Offer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Offer)
                    @Html.ValidationMessageFor(model => model.Offer, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IS7/Views/Interviews/Index.cshtml
@model IEnumerable<IS7.Models.Interview>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<p>
    @using (Html.BeginForm("Index", "Interviews", FormMethod.Get))
    {
        <b>Search By:</b>
        @Html.RadioButton("searchBy", "MNumber", true) <text>MNumber</text>
        @Html.RadioButton("searchBy", "InterviewCompany") <text>InterviewCompany</text>
        <br />
        @Html.TextBox("search")<input type="submit" value="Search" />
    }
</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.User.MNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InterviewCompany)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InterviewDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Offer)
        </th>

        <th></th>
    </tr>
    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="8">No rows match search criteria</td>
        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.User.MNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.User.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InterviewCompany)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InterviewDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Offer)
                </td>

                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    }
    </table>